### ISSUE TITLE
Pass bypass-invite-token to planetary.name start command

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/rooms-frontend#126]
The go-ssb-room server at Planetary.name didn't have the -bypass-invite-token set. This is the token that the Planetary iOS app embeds and uses to join the room. I added it manually by writing a custom start script for the container named `tmp_start.sh` and mounting it as a volume in docker-compose file at /root/room/docker-compose.yml.

@cooldracula can you update your ansible scripts to include this flag?

**Comment by cooldracula** [comment]
I've updated the start script and docker file for go-ssb-room, seen in [pr #7](https://github.com/planetary-social/go-ssb-room/pull/7)

I then updated the ansible scripts to pass this env var to the docker image, in [pr #21](https://github.com/planetary-social/ansible-scripts/pull/21)
