### ISSUE TITLE
update ansible playbook for building go-ssb-rooms and view front end

### ISSUE THREAD

**Issue by rabble** [planetary-social/rooms-frontend#23]

**Comment by mplorentz** [comment]
See also https://github.com/planetary-social/infrastructure/issues/28

**Comment by danlatorre** [comment]
Q: from Nov 21 sprint planning - Need to clarify how 'view front end' work is part of this and to what degree.

**Comment by rabble** [comment]
Need to check in with Zach about the status of this.

**Comment by cooldracula** [comment]
This is addressed, indirectly, in https://github.com/planetary-social/rooms-frontend/issues/23

The suggestion in that PR is to containerize these applications via docker.  Anytime you update the code, you would build a new docker image, tag it, and push it to your repo.   

The host would be running three docker services and to update any of them, you would run an ansible task that changes the docker tag used for the service and restarts it.

This containerized setup, and the ansible tasks, are included in the above PR.  There are pr's for go-ssb-room([#2](https://github.com/planetary-social/go-ssb-room/pull/4)), graphql([#43](https://github.com/planetary-social/planetary-graphql/pull/43)), and the rooms-frontend([#130](https://github.com/planetary-social/rooms-frontend/pull/103)) to containerize each of these services.

**Comment by boreq** [comment]
This is assigned to me, presumably because of #56, but I am not sure if it should be at this point.
