### ISSUE TITLE
Login Button

### ISSUE THREAD

**Issue by chereseeriepa** [planetary-social/rooms-frontend#36]
Add the login button to the UI, it should take you to `https://civic.love/login`

**Comment by rabble** [comment]
I don't think so actually. Because most users logging in will not be trying to login to manage the room. Most users hitting login will be trying to figure out how ot use the planetary ios app. We need to talk about this with Daniel and Sebastian.

**Comment by danlatorre** [comment]
Dependent on #941

**Comment by rabble** [comment]
https://github.com/planetary-social/planetary-ios/issues/941
