### ISSUE TITLE
Change where rooms frontend assets are served

### ISSUE THREAD

**Issue by chereseeriepa** [planetary-social/rooms-frontend#56]
Need to change the location of where the frontend dist files are being served to make it easier for them to be replaced / overwritten by either manually (by someone) or automatic (through ansible)

The idea is that when someone creates a new production build of `rooms-frontend` (which each individual room will need to do in order to apply custom environment variables to the `rooms-frontend`), this change makes it a lot easier to overwrite the whole folder, rather than figuring out manually which ones need to be replaced/removed. This will then be a lot easier for the ansible script that will automate that process.

Proposed solution:
- instead of serving them at `go-ssb-room/web/assets` they are served at `go-ssb-room/web/assets/app` or something similar
- need to update the route that points to the assets, to point to this subfolder instead

**Comment by boreq** [comment]
@chereseeriepa https://github.com/planetary-social/go-ssb-room/pull/3/commits/5e2a2da80877facb1d80a7e8508a82f74799e9d7

I hcanged the way the assets are loaded. First we try to load
assets from `web/app` and if that fails we load them from `web/assets`. This
means that files can be in either one of those directories with web/app
taking priority.

So basically you should be able to move all your app files to `web/app` and keep them there. I moved 3 files for now as I wasn't sure which files belong to the frontend app and which are the part of the rooms.

Let me know if this works for you.

**Comment by boreq** [comment]
Ok for now I fixed the dev server to also serve assets from `web/app` and then from `web/assets` if they are missing. This means that it should behave like the production server. 

Do we also want to do the other requirement as part of this ticket ("_by default, it should show the old UI when there is no web/app (its currently showing a list of the assets on the landing page instead_") or is there a separate one for this?
