### ISSUE TITLE
Get info for whats an ssb app?

### ISSUE THREAD

**Issue by chereseeriepa** [planetary-social/rooms-frontend#68]
This is for the "Whats an SSB app?" button

**Comment by Chardot** [comment]
Yes, that should link to an external page explaining what’s SSB and how to use it. For now we can link to scuttlebutt.nz but in the future we will include a page in our website explaining this with more visuals.Sent from my iPhoneOn 24 Nov 2022, at 03:45, Cherese Eriepa ***@***.***> wrote:﻿
@Chardot does "What's an SSB app?" take you to another page/website
