### ISSUE TITLE
Get invite code from the room server

### ISSUE THREAD

**Issue by chereseeriepa** [planetary-social/rooms-frontend#69]
## Problem

We dont have the invite code to join a room.

## Proposed solution:

Extend the create-invite endpoint on the room server to return the invite code as json

E.g.

```
https://civic.love/create-invite?encoding=json
```

returns the invite code:

```
https://civic.love/join?token=A3XeKco802sJlr-IaJCz7iQfy_-sIcI-mTrrPkP69WFPhrMSZqTdSw04CXkOBn4AlLA%3D
```

![Image](https://user-images.githubusercontent.com/14947625/203685995-dff34a7d-0719-4495-a205-261dd3f89b3c.png)

**Comment by boreq** [comment]
https://github.com/planetary-social/go-ssb-room/pull/5

**Comment by boreq** [comment]
And the upstream pull request is here. 

https://github.com/ssbc/go-ssb-room/pull/368

**Comment by boreq** [comment]
Closing as both PRs are merged.
